# Generated by Django 5.0.1 on 2024-02-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Task',
        ),
    ]
