# Generated by Django 5.0.1 on 2024-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rename_todo_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
